// Catálogo de temas del examen. El `id` es estable y viaja al plan y al
// historial; el `text` puede reescribirse sin invalidar historial. Un tema
// puede servir a varias secciones (etiquetas en `sections`).
//
// t-001..t-057: copiados literalmente desde TEFAQ_TOPICS en
// backend/src/prompt.js (líneas 3-59, en su orden original). Nota: el brief
// de esta tarea hablaba de "59 entradas originales", pero el array real en
// prompt.js contiene 57 strings, no 59 (verificado contando el array en
// tiempo de ejecución y leyendo el archivo). Se usa el conteo real (57)
// para no inventar entradas "originales" inexistentes.
// t-058 en adelante: temas nuevos, redactados para cubrir los mínimos de
// pool por sección exigidos por backend/test/catalog.test.js.
export const TOPICS = [
  // ---- t-001..t-057: copiados literalmente de prompt.js ----
  { id: 't-001', text: 'Un problema de mantenimiento en un departamento o edificio en Quebec (ej. calefacción, plomería, ruido de vecinos).', sections: ['repondeur', 'divers'] },
  { id: 't-002', text: 'Un anuncio en el transporte público de Montreal (ej. metro, autobús, STM) sobre un retraso, desvío o normas de cortesía.', sections: ['annonce_publique', 'divers'] },
  { id: 't-003', text: 'Una conversación de trabajo sobre el teletrabajo, una reunión pospuesta, o un conflicto menor en la oficina.', sections: ['divers'] },
  { id: 't-004', text: 'Un mensaje en el contestador sobre la cancelación, reprogramación de una cita médica o un servicio no entregado.', sections: ['repondeur', 'divers'] },
  { id: 't-005', text: 'Un fragmento de radio debatiendo un tema de actualidad (ej. uso de redes sociales, inflación en el supermercado, medio ambiente).', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-006', text: 'Una conversación informal entre amigos planeando una actividad típica (ej. ir a un chalet, esquí, festival de verano).', sections: ['divers'] },
  { id: 't-007', text: 'Un cliente haciendo una queja o pidiendo información sobre facturación en un servicio al cliente (telefonía, internet).', sections: ['repondeur', 'divers'] },
  { id: 't-008', text: 'Instrucciones o nuevas normativas en un espacio público (ej. gimnasio, biblioteca, universidad).', sections: ['annonce_publique', 'divers'] },
  { id: 't-009', text: 'una llamada al servicio al cliente de un banco (Desjardins, RBC, etc.)', sections: ['repondeur', 'divers'] },
  { id: 't-010', text: 'un reporte del clima en la radio (frío, nieve, tormenta)', sections: ['annonce_publique', 'divers'] },
  { id: 't-011', text: 'una reclamación en una tienda o un dépanneur', sections: ['divers'] },
  { id: 't-012', text: 'una reservación por teléfono en un restaurante', sections: ['repondeur', 'divers'] },
  { id: 't-013', text: 'un trámite en la SAAQ (licencia, registro de auto)', sections: ['repondeur', 'divers'] },
  { id: 't-014', text: 'un mensaje de la escuela o la guardería (CPE) de un niño', sections: ['repondeur', 'divers'] },
  { id: 't-015', text: 'una conversación con un vecino sobre la recolección de basura o reciclaje', sections: ['micro_trottoir', 'divers'] },
  { id: 't-016', text: 'un anuncio de ofertas en un supermercado (IGA, Metro, Provigo)', sections: ['annonce_publique', 'divers'] },
  { id: 't-017', text: 'una conversación sobre la búsqueda de empleo o una entrevista', sections: ['divers'] },
  { id: 't-018', text: 'un mensaje de Hydro-Québec sobre un corte de electricidad', sections: ['annonce_publique', 'repondeur', 'divers'] },
  { id: 't-019', text: 'una invitación a una fiesta o un 5 à 7 entre amigos', sections: ['divers'] },
  { id: 't-020', text: 'una conversación sobre un viaje por carretera a Québec o a las Laurentides', sections: ['divers'] },
  { id: 't-021', text: 'un reclamo de seguro de auto o de vivienda', sections: ['repondeur', 'divers'] },
  { id: 't-022', text: 'una conversación con un funcionario de Immigration Québec o del municipio', sections: ['repondeur', 'divers'] },
  { id: 't-023', text: 'un boletín de radio sobre una nueva medida municipal de estacionamiento en Montreal', sections: ['chronique', 'reportage', 'micro_trottoir', 'divers'] },
  { id: 't-024', text: 'una noticia local sobre obras viales que afectan el acceso a un barrio o puente', sections: ['reportage', 'micro_trottoir', 'divers'] },
  { id: 't-025', text: 'un aviso del municipio sobre una consulta pública para un proyecto de vivienda', sections: ['annonce_publique', 'micro_trottoir', 'reportage'] },
  { id: 't-026', text: 'una cápsula informativa sobre aumento de alquileres y derechos de los inquilinos', sections: ['chronique', 'reportage', 'micro_trottoir'] },
  { id: 't-027', text: 'una entrevista breve con una asociación de vecinos sobre ruido, seguridad o limpieza', sections: ['interview', 'micro_trottoir'] },
  { id: 't-028', text: 'un anuncio de salud pública sobre vacunación, clínica sin cita o prevención estacional', sections: ['annonce_publique', 'divers'] },
  { id: 't-029', text: 'una noticia sobre cambios en el sistema de salud, una clínica cerrada o tiempos de espera', sections: ['reportage', 'chronique', 'micro_trottoir'] },
  { id: 't-030', text: 'un segmento de radio sobre educación, huelga escolar o cambios en el calendario académico', sections: ['chronique', 'reportage', 'micro_trottoir'] },
  { id: 't-031', text: 'un mensaje universitario sobre inscripción, becas, examen aplazado o servicio estudiantil', sections: ['repondeur', 'divers'] },
  { id: 't-032', text: 'un aviso sobre francisation, curso de francés gratuito o cambio de horario en un centro comunitario', sections: ['annonce_publique', 'divers'] },
  { id: 't-033', text: 'una conversación sobre impuestos, declaración fiscal, Revenu Québec o un documento faltante', sections: ['repondeur', 'divers'] },
  { id: 't-034', text: 'un aviso de Élections Québec sobre inscripción electoral, lugar de votación o fecha límite', sections: ['annonce_publique', 'divers'] },
  { id: 't-035', text: 'un debate corto en radio sobre una promesa electoral provincial o municipal', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-036', text: 'una noticia sobre transporte público: aumento de tarifas, nueva línea, interrupción o accesibilidad', sections: ['reportage', 'chronique', 'micro_trottoir'] },
  { id: 't-037', text: 'un anuncio de aeropuerto o estación de tren sobre retraso, equipaje o cambio de puerta', sections: ['annonce_publique', 'divers'] },
  { id: 't-038', text: 'una cápsula de consumo sobre garantía legal, devolución de producto o contrato cancelado', sections: ['chronique', 'divers'] },
  { id: 't-039', text: 'una llamada con una compañía de energía o telecomunicaciones sobre un contrato promocional', sections: ['repondeur', 'divers'] },
  { id: 't-040', text: 'una noticia ambiental sobre compostaje, reciclaje, calidad del aire o restricciones de agua', sections: ['chronique', 'reportage', 'micro_trottoir'] },
  { id: 't-041', text: 'un aviso de seguridad pública sobre tormenta, inundación, ola de calor o evacuación preventiva', sections: ['annonce_publique', 'divers'] },
  { id: 't-042', text: 'una conversación laboral sobre sindicato, convenio colectivo, horas extra o cambio de turno', sections: ['divers'] },
  { id: 't-043', text: 'un mensaje de recursos humanos sobre formación obligatoria, beneficios o evaluación anual', sections: ['repondeur', 'divers'] },
  { id: 't-044', text: 'una entrevista de radio con un comerciante afectado por obras, inflación o falta de personal', sections: ['interview', 'chronique', 'micro_trottoir'] },
  { id: 't-045', text: 'un anuncio cultural sobre festival, museo, espectáculo cancelado o cambio de programación', sections: ['annonce_publique', 'divers'] },
  { id: 't-046', text: 'una crónica cultural sobre cine quebequense, música local o evento comunitario', sections: ['divers'] },
  { id: 't-047', text: 'una noticia deportiva local sobre cierre de instalaciones, inscripción o cambio de horario', sections: ['divers'] },
  { id: 't-048', text: 'un aviso de biblioteca sobre préstamo vencido, actividad gratuita o sala reservada', sections: ['annonce_publique', 'repondeur', 'divers'] },
  { id: 't-049', text: 'una conversación sobre compra de auto usado, inspección mecánica o garantía', sections: ['divers'] },
  { id: 't-050', text: 'un aviso de condominio sobre asamblea, presupuesto, reparación urgente o reglas comunes', sections: ['annonce_publique', 'repondeur', 'divers'] },
  { id: 't-051', text: 'una llamada sobre guardería, lista de espera, subsidio o ausencia de educadora', sections: ['repondeur', 'divers'] },
  { id: 't-052', text: 'una noticia sobre inmigración, reconocimiento de diplomas o integración laboral', sections: ['chronique', 'reportage', 'interview'] },
  { id: 't-053', text: 'un mensaje de una organización comunitaria sobre banco de alimentos, voluntariado o donaciones', sections: ['repondeur', 'divers'] },
  { id: 't-054', text: 'una conversación sobre una cita con notario, contrato de arrendamiento o documento oficial', sections: ['repondeur', 'divers'] },
  { id: 't-055', text: 'un boletín económico breve sobre precios de alimentos, tasas de interés o empleo en Quebec', sections: ['chronique', 'reportage'] },
  { id: 't-056', text: 'una opinión de radio sobre redes sociales, privacidad, inteligencia artificial o desinformación', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-057', text: 'una entrevista breve sobre turismo regional, temporada alta o recomendaciones para visitantes', sections: ['divers'] },

  // ---- t-058..t-067: avisos/anuncios públicos nuevos ----
  { id: 't-058', text: 'un anuncio en la estación de metro de Montreal sobre el cierre temporal de una línea por mantenimiento', sections: ['annonce_publique', 'divers'] },
  { id: 't-059', text: 'un aviso en un centro comercial sobre el cierre anticipado por una tormenta de nieve', sections: ['annonce_publique', 'divers'] },
  { id: 't-060', text: 'un anuncio en un CLSC sobre el cambio de horario de la clínica sin cita', sections: ['annonce_publique', 'divers'] },
  { id: 't-061', text: 'un aviso en un parque municipal sobre restricciones de uso por trabajos de mantenimiento', sections: ['annonce_publique', 'divers'] },
  { id: 't-062', text: 'un anuncio en la SQDC sobre límites de compra y nuevas normas de identificación', sections: ['annonce_publique', 'divers'] },
  { id: 't-063', text: 'un aviso en un edificio público sobre un ascensor fuera de servicio de forma temporal', sections: ['annonce_publique', 'divers'] },
  { id: 't-064', text: 'un anuncio en una farmacia (Jean Coutu, Uniprix) sobre un nuevo servicio de vacunación sin cita', sections: ['annonce_publique', 'divers'] },
  { id: 't-065', text: 'un aviso en una estación del REM o de un tren de cercanías sobre un cambio de itinerario', sections: ['annonce_publique', 'divers'] },
  { id: 't-066', text: 'un anuncio en un arena municipal sobre el cierre de la pista de patinaje por reparaciones', sections: ['annonce_publique', 'divers'] },
  { id: 't-067', text: 'un aviso en la entrada de un edificio de oficinas sobre una prueba de alarma de incendio programada', sections: ['annonce_publique', 'divers'] },

  // ---- t-068..t-083: mensajes de contestador nuevos ----
  { id: 't-068', text: 'un mensaje del CLSC confirmando una cita con un médico de familia', sections: ['repondeur', 'divers'] },
  { id: 't-069', text: 'un mensaje de un taller mecánico avisando que el auto ya está listo para recoger', sections: ['repondeur', 'divers'] },
  { id: 't-070', text: 'un mensaje de una clínica dental cancelando una cita por una emergencia del dentista', sections: ['repondeur', 'divers'] },
  { id: 't-071', text: 'un mensaje de Revenu Québec pidiendo un documento adicional para completar un trámite', sections: ['repondeur', 'divers'] },
  { id: 't-072', text: 'un mensaje de Emploi-Québec convocando a una entrevista de trabajo', sections: ['repondeur', 'divers'] },
  { id: 't-073', text: 'un mensaje de un plomero confirmando la hora de una visita para una reparación', sections: ['repondeur', 'divers'] },
  { id: 't-074', text: 'un mensaje de la guardería avisando que hay que recoger a un niño antes de lo habitual', sections: ['repondeur', 'divers'] },
  { id: 't-075', text: 'un mensaje de un veterinario sobre el resultado de un examen de la mascota', sections: ['repondeur', 'divers'] },
  { id: 't-076', text: 'un mensaje de una aerolínea sobre un cambio de horario de vuelo', sections: ['repondeur', 'divers'] },
  { id: 't-077', text: 'un mensaje del gimnasio sobre la renovación o cancelación de una membresía', sections: ['repondeur', 'divers'] },
  { id: 't-078', text: 'un mensaje de una empresa de mudanzas confirmando la fecha y hora de entrega de las cajas', sections: ['repondeur', 'divers'] },
  { id: 't-079', text: 'un mensaje de un salón de belleza o peluquería reprogramando una cita', sections: ['repondeur', 'divers'] },
  { id: 't-080', text: 'un mensaje de un seguro de salud privado sobre un reembolso pendiente', sections: ['repondeur', 'divers'] },
  { id: 't-081', text: 'un mensaje de la oficina del arrendador sobre una visita para reparar un electrodoméstico', sections: ['repondeur', 'divers'] },
  { id: 't-082', text: 'un mensaje de un notario confirmando la firma de un contrato de compra de vivienda', sections: ['repondeur', 'divers'] },
  { id: 't-083', text: 'un mensaje de un hospital sobre el resultado de un análisis de laboratorio', sections: ['repondeur', 'divers'] },

  // ---- t-084..t-102: micro-trottoirs nuevos (temas opinables de calle) ----
  { id: 't-084', text: 'una entrevista de calle sobre la nueva vignette de estacionamiento residencial en un barrio', sections: ['micro_trottoir', 'reportage', 'divers'] },
  { id: 't-085', text: 'una entrevista de calle sobre la prohibición de bolsas de plástico en los comercios', sections: ['micro_trottoir', 'chronique'] },
  { id: 't-086', text: 'una entrevista de calle sobre el nuevo sistema de recolección de residuos orgánicos (bac brun)', sections: ['micro_trottoir', 'chronique'] },
  { id: 't-087', text: 'una entrevista de calle sobre la instalación de nuevas ciclovías en el centro de la ciudad', sections: ['micro_trottoir', 'reportage'] },
  { id: 't-088', text: 'una entrevista de calle sobre el aumento del precio de la vivienda en Montreal', sections: ['micro_trottoir', 'chronique', 'reportage'] },
  { id: 't-089', text: 'una entrevista de calle sobre la regulación de los alquileres tipo Airbnb en zonas residenciales', sections: ['micro_trottoir', 'chronique'] },
  { id: 't-090', text: 'una entrevista de calle sobre el uso del teléfono celular al caminar o conducir', sections: ['micro_trottoir', 'divers'] },
  { id: 't-091', text: 'una entrevista de calle sobre el cambio de hora entre horario de verano e invierno', sections: ['micro_trottoir', 'divers'] },
  { id: 't-092', text: 'una entrevista de calle sobre la costumbre de dejar propina en los restaurantes de Quebec', sections: ['micro_trottoir', 'divers'] },
  { id: 't-093', text: 'una entrevista de calle sobre el ruido de las obras de construcción en el barrio', sections: ['micro_trottoir', 'divers'] },
  { id: 't-094', text: 'una entrevista de calle sobre la falta de estacionamiento en el centro de la ciudad', sections: ['micro_trottoir', 'divers'] },
  { id: 't-095', text: 'una entrevista de calle sobre la limpieza de las calles después del invierno', sections: ['micro_trottoir', 'divers'] },
  { id: 't-096', text: 'una entrevista de calle sobre el aumento de las cuentas de electricidad en invierno', sections: ['micro_trottoir', 'chronique'] },
  { id: 't-097', text: 'una entrevista de calle sobre la presencia de campamentos de personas en situación de calle', sections: ['micro_trottoir', 'chronique', 'reportage'] },
  { id: 't-098', text: 'una entrevista de calle sobre la instalación de cámaras de seguridad en un parque', sections: ['micro_trottoir', 'divers'] },
  { id: 't-099', text: 'una entrevista de calle sobre la reducción de velocidad en zonas escolares', sections: ['micro_trottoir', 'chronique'] },
  { id: 't-100', text: 'una entrevista de calle sobre el ruido de los espectáculos al aire libre en verano', sections: ['micro_trottoir', 'divers'] },
  { id: 't-101', text: 'una entrevista de calle sobre la instalación de un nuevo semáforo peatonal', sections: ['micro_trottoir', 'divers'] },
  { id: 't-102', text: 'una entrevista de calle sobre la calidad del servicio de taxis y aplicaciones de transporte', sections: ['micro_trottoir', 'divers'] },

  // ---- t-103..t-140: bloque 3 (debate y actualidad) ----
  { id: 't-103', text: 'un debate en radio sobre las promesas de las elecciones municipales en Montreal', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-104', text: 'una crónica de radio sobre el aumento de la tasa de interés hipotecaria en Quebec', sections: ['chronique', 'reportage'] },
  { id: 't-105', text: 'una entrevista con un economista sobre la inflación del precio de los alimentos', sections: ['interview', 'chronique'] },
  { id: 't-106', text: 'un reportaje sobre la escasez de mano de obra en el sector de la construcción', sections: ['reportage', 'chronique'] },
  { id: 't-107', text: 'una entrevista con un especialista en salud sobre la saturación de las salas de urgencia', sections: ['interview', 'chronique'] },
  { id: 't-108', text: 'un reportaje sobre la falta de médicos de familia y las listas de espera de acceso a un médico', sections: ['reportage', 'chronique'] },
  { id: 't-109', text: 'una crónica sobre la reforma del sistema de salud en Quebec', sections: ['chronique', 'interview'] },
  { id: 't-110', text: 'un debate en radio sobre la ley sobre la laicidad del Estado', sections: ['chronique', 'interview'] },
  { id: 't-111', text: 'una entrevista sobre la ley del francés y su aplicación en el comercio', sections: ['interview', 'chronique'] },
  { id: 't-112', text: 'un reportaje sobre el aumento de los umbrales de inmigración en Quebec', sections: ['reportage', 'chronique', 'interview'] },
  { id: 't-113', text: 'una entrevista con un inmigrante recién llegado sobre el proceso de francización', sections: ['interview', 'chronique'] },
  { id: 't-114', text: 'un reportaje sobre el reconocimiento de trabajadores extranjeros temporales', sections: ['reportage', 'chronique'] },
  { id: 't-115', text: 'una crónica sobre el impacto del cambio climático en las tormentas de invierno', sections: ['chronique', 'reportage'] },
  { id: 't-116', text: 'un reportaje sobre la calidad del aire durante los incendios forestales del verano', sections: ['reportage', 'chronique'] },
  { id: 't-117', text: 'una entrevista con un ambientalista sobre la reducción de plásticos de un solo uso', sections: ['interview', 'chronique'] },
  { id: 't-118', text: 'un debate en radio sobre la construcción de un tercer enlace (troisième lien) en Quebec', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-119', text: 'un reportaje sobre la construcción del tranvía de la ciudad de Quebec', sections: ['reportage', 'chronique'] },
  { id: 't-120', text: 'un reportaje sobre las demoras del REM de l’Est y su impacto en el este de Montreal', sections: ['reportage', 'chronique'] },
  { id: 't-121', text: 'una entrevista con un profesor sobre la escasez de docentes en las escuelas públicas', sections: ['interview', 'chronique'] },
  { id: 't-122', text: 'un reportaje sobre el aumento de los costos universitarios para estudiantes internacionales', sections: ['reportage', 'chronique'] },
  { id: 't-123', text: 'una crónica sobre la deserción escolar y las medidas para reducirla', sections: ['chronique', 'reportage'] },
  { id: 't-124', text: 'una entrevista con un experto en tecnología sobre el impacto de la inteligencia artificial en el empleo', sections: ['interview', 'chronique'] },
  { id: 't-125', text: 'un debate en radio sobre una nueva ley de protección de datos personales', sections: ['chronique', 'interview'] },
  { id: 't-126', text: 'un reportaje sobre el fraude telefónico y las estafas dirigidas a personas mayores', sections: ['reportage', 'chronique'] },
  { id: 't-127', text: 'una entrevista sobre el uso excesivo de las pantallas en los niños', sections: ['interview', 'chronique'] },
  { id: 't-128', text: 'una crónica sobre el auge de los vehículos eléctricos y las bornas de recarga en Quebec', sections: ['chronique', 'reportage'] },
  { id: 't-129', text: 'un reportaje sobre una huelga del sector público y las negociaciones sindicales', sections: ['reportage', 'chronique'] },
  { id: 't-130', text: 'una entrevista con un representante sindical sobre la escasez de enfermeras', sections: ['interview', 'chronique'] },
  { id: 't-131', text: 'un debate en radio sobre el salario mínimo en Quebec', sections: ['chronique', 'interview'] },
  { id: 't-132', text: 'una crónica sobre la crisis de la vivienda asequible en las grandes ciudades', sections: ['chronique', 'reportage'] },
  { id: 't-133', text: 'un reportaje sobre la gentrificación de un barrio popular de Montreal', sections: ['reportage', 'chronique'] },
  { id: 't-134', text: 'una entrevista con un urbanista sobre la densificación de los barrios residenciales', sections: ['interview', 'chronique'] },
  { id: 't-135', text: 'un debate en radio sobre un referéndum municipal para un proyecto de desarrollo', sections: ['chronique', 'interview', 'micro_trottoir'] },
  { id: 't-136', text: 'una crónica sobre una propuesta de reforma del modo de escrutinio en las elecciones provinciales', sections: ['chronique', 'interview'] },
  { id: 't-137', text: 'un reportaje sobre la evaluación de propiedades y el aumento de los impuestos municipales', sections: ['reportage', 'chronique'] },
  { id: 't-138', text: 'una entrevista con un concejal municipal sobre el presupuesto de la ciudad', sections: ['interview', 'chronique'] },
  { id: 't-139', text: 'un reportaje sobre la crisis de opioides y los servicios de salud pública', sections: ['reportage', 'chronique'] },
  { id: 't-140', text: 'una entrevista con un trabajador social sobre la violencia conyugal y los recursos de ayuda disponibles', sections: ['interview', 'chronique'] },

  // ---- t-141..t-152: vida cotidiana adicional ----
  { id: 't-141', text: 'una conversación sobre planificar una salida familiar al Biodôme o al Jardín Botánico de Montreal', sections: ['divers'] },
  { id: 't-142', text: 'una llamada a una clínica veterinaria para agendar la vacunación anual de una mascota', sections: ['repondeur', 'divers'] },
  { id: 't-143', text: 'una conversación sobre la búsqueda de un CPE con cupo disponible para un bebé', sections: ['divers'] },
  { id: 't-144', text: 'un mensaje sobre la entrega retrasada de un paquete pedido en línea', sections: ['repondeur', 'divers'] },
  { id: 't-145', text: 'una conversación sobre la renovación de un contrato de arrendamiento antes del 1 de julio', sections: ['divers'] },
  { id: 't-146', text: 'una llamada para agendar una cita en la SAAQ para un examen de manejo', sections: ['repondeur', 'divers'] },
  { id: 't-147', text: 'una conversación sobre la elección de un plan de telefonía móvil más económico', sections: ['divers'] },
  { id: 't-148', text: 'un mensaje del banco Desjardins sobre una transacción sospechosa en la cuenta', sections: ['repondeur', 'divers'] },
  { id: 't-149', text: 'una conversación entre colegas sobre organizar una actividad de team building', sections: ['divers'] },
  { id: 't-150', text: 'un aviso sobre el cierre de una piscina municipal por mantenimiento de verano', sections: ['annonce_publique', 'divers'] },
  { id: 't-151', text: 'una conversación sobre inscribir a un niño en actividades extracurriculares en el barrio', sections: ['divers'] },
  { id: 't-152', text: 'un mensaje de un contratista sobre el presupuesto de una renovación en casa', sections: ['repondeur', 'divers'] },
];

export function topicsForSection(sectionType, catalog = TOPICS) {
  return catalog.filter(topic => topic.sections.includes(sectionType));
}

export function topicById(id, catalog = TOPICS) {
  return catalog.find(topic => topic.id === id);
}
